// packages/angular/src/block-portal-registry.ts
// packages/angular/src/block-portal-registry.ts
import {
  ApplicationRef,
  createComponent,
  EnvironmentInjector,
  ErrorHandler,
  Injector,
  type ComponentRef,
  type Signal,
  type Type,
} from '@angular/core';

import type { Blok } from '@/types';

import { BLOK_BLOCK_CONTEXT, type AngularBlockRenderContext } from './block-context';
import { BLOK_EDITOR_INSTANCE } from './blok-instance';

/**
 * Tool-config key carrying the editor's portal registry into a
 * `createAngularBlock` tool. The tool is constructed by CORE (outside any Angular
 * injection context), so it cannot `inject()` — the directive injects the
 * editor-scoped registry through each Angular-block tool's `config`, and the tool
 * reads it back from there.
 */
export const BLOK_PORTAL_REGISTRY_CONFIG_KEY = '__blokAngularPortalRegistry';

/** One mounted Angular block: the Blok-owned host the component renders into. */
export interface BlockPortalEntry {
  hostEl: HTMLElement;
  component: Type<unknown>;
  context: AngularBlockRenderContext<unknown>;
}

/**
 * Per-editor registry of Angular blocks. Mounts each authored component directly
 * into its core-owned host via `createComponent({ hostElement })` (the Teleport
 * analog) and enrolls it in `ApplicationRef` for change detection. A plain Map —
 * Angular has no reactive-proxy hazard, so no `markRaw` equivalent is needed.
 */
export interface BlockPortalRegistry {
  /** Mount (or replace) the component for `id` into `entry.hostEl`. */
  register(id: string, entry: BlockPortalEntry): void;
  /**
   * Detach + destroy the component for `id`. Safe (no-op) when absent.
   *
   * Pass the caller's own `hostEl` to make the teardown OWNERSHIP-CHECKED: the
   * mount is destroyed only when it is still the one that host registered. Core
   * composes a replacement block (which registers under the SAME id) BEFORE it
   * destroys the block it replaces, so a superseded tool's `removed()`/
   * `destroy()` teardown arrives after the live mount already exists — without
   * the check it destroys that live componentRef and clears its host.
   */
  unregister(id: string, hostEl?: HTMLElement): void;
  /** Re-run change detection on the block's component (in-place update). */
  flush(id: string): void;
  /** Detach + destroy every mounted block (editor teardown / recreate). */
  destroyAll(): void;
}

/**
 * Create a fresh portal registry bound to a live Angular environment. One per
 * editor instance (associated via the registry map). The injectors/appRef are
 * passed in (captured by the directive in an injection context) because the
 * registry itself is built outside one.
 *
 * `editor` is the directive's own instance signal. It is passed at CREATION
 * (before the editor exists) rather than set later precisely because it is a
 * signal: blocks mounted during boot read null and re-read the real instance
 * once it resolves.
 * @param envInjector - the app environment injector (parent of each block's)
 * @param appRef - the ApplicationRef each mounted block view is attached to
 * @param errorHandler - where a throwing author component is reported
 * @param editor - signal of the live Blok instance, published to blocks via
 *   {@link BLOK_EDITOR_INSTANCE}; omit for registries with no editor to publish
 */
export const createBlockPortalRegistry = (
  envInjector: EnvironmentInjector,
  appRef: ApplicationRef,
  errorHandler: ErrorHandler,
  editor?: Signal<Blok | null>
): BlockPortalRegistry => {
  const mounted = new Map<string, { ref: ComponentRef<unknown>; injector: Injector }>();

  // Change detection runs outside NgZone here; a throwing author component must
  // degrade to a blank holder, not break core's block insertion.
  const safe = (fn: () => void): void => {
    try {
      fn();
    } catch (error) {
      errorHandler.handleError(error);
    }
  };

  const teardown = (id: string, ownerHostEl?: HTMLElement): void => {
    const entry = mounted.get(id);

    if (entry === undefined) {
      return;
    }

    const { ref, injector } = entry;
    // Capture host before deletion so we can clear it below.
    const hostEl = ref.location.nativeElement as HTMLElement;

    // A superseded owner may not destroy the mount that replaced it.
    if (ownerHostEl !== undefined && hostEl !== ownerHostEl) {
      return;
    }

    mounted.delete(id);
    appRef.detachView(ref.hostView);
    ref.destroy();
    // `Injector.create({ parent })` returns an injector that is NOT torn down by
    // `ref.destroy()`. We must destroy it explicitly to prevent one small injector
    // accumulating per block over a long editor session.
    const destroyable = injector as Injector & { destroy?: () => void };
    destroyable.destroy?.();
    // createComponent({ hostElement }) renders INTO an external div. Angular's
    // destroy() tears down the component instance and CD but does NOT clear the
    // host's DOM children — we must do it explicitly.
    hostEl.replaceChildren();
  };

  return {
    register(id: string, entry: BlockPortalEntry): void {
      // Idempotent: replace any prior mount for this id.
      teardown(id);

      // The context is provided through an ELEMENT injector (a node injector),
      // so it is destroyed automatically with the component view — no leaked
      // EnvironmentInjector. The shared app envInjector is the parent, so author
      // blocks still see app-level providers (HttpClient, etc.).
      const elementInjector = Injector.create({
        providers: [
          { provide: BLOK_BLOCK_CONTEXT, useValue: entry.context },
          // Per-EDITOR, so two editors on one page each publish their own
          // instance to their own blocks.
          ...(editor === undefined
            ? []
            : [{ provide: BLOK_EDITOR_INSTANCE, useValue: editor }]),
        ],
        parent: envInjector,
      });

      safe(() => {
        const ref = createComponent(entry.component, {
          environmentInjector: envInjector,
          elementInjector,
          hostElement: entry.hostEl,
        });

        appRef.attachView(ref.hostView);
        mounted.set(id, { ref, injector: elementInjector });
        // createComponent does not auto-run CD; render synchronously into the
        // (still-detached) host before core inserts it into the document.
        ref.changeDetectorRef.detectChanges();
      });
    },
    unregister(id: string, hostEl?: HTMLElement): void {
      teardown(id, hostEl);
    },
    flush(id: string): void {
      const entry = mounted.get(id);

      if (entry === undefined) {
        return;
      }

      safe(() => entry.ref.changeDetectorRef.detectChanges());
    },
    destroyAll(): void {
      for (const id of Array.from(mounted.keys())) {
        teardown(id);
      }
    },
  };
};

// packages/react/src/block-portal-registry.ts
import type { ComponentType } from 'react';

/**
 * Tool-config key carrying the editor's portal registry into a
 * `createReactBlock` tool. The tool is constructed by CORE (outside any React
 * render), so it cannot read context — `useBlok` injects the editor-scoped
 * registry through each react-block tool's `config`, and the tool reads it here.
 */
export const BLOK_PORTAL_REGISTRY_CONFIG_KEY = '__blokPortalRegistry';

/**
 * Tool-config key carrying the name the tool was registered under in the
 * consumer's `tools` map (injected next to the registry). The factory needs it
 * to associate portal entries with their tool so live config updates can be
 * routed; it is stripped (with the registry key) before the sanitized config
 * reaches the component.
 */
export const BLOK_TOOL_NAME_CONFIG_KEY = '__blokToolName';

/**
 * One mounted React block in the portal registry. `hostEl` is the Blok-owned
 * `toolRenderedElement` (tagged `data-blok-mutation-free`) the component is
 * portaled into; `props` is replaced immutably by `setProps` so the mounted
 * component re-renders in place (no remount).
 */
export interface BlockPortalEntry {
  hostEl: HTMLElement;
  component: ComponentType<Record<string, unknown>>;
  props: Record<string, unknown>;
  /** Name the tool is registered under — routes per-tool live config updates. */
  toolName?: string;
}

/**
 * Per-editor registry of React blocks. A single shared `BlockPortalHost`
 * renders one `createPortal` per entry, so every block lives in ONE React tree
 * (shared context, one reconciler) — the TipTap ReactNodeViewRenderer pattern,
 * not a `createRoot` per block.
 *
 * Shaped as an external store (`subscribe`/`getSnapshot`) so the host can read
 * it through `useSyncExternalStore`. The snapshot is immutable: every mutation
 * replaces it, and `getSnapshot` is referentially stable between mutations.
 */
export interface BlockPortalRegistry {
  /**
   * Register (or replace) the entry for `id`. Idempotent: a second register
   * for the same id replaces the entry rather than mounting a duplicate.
   */
  register(id: string, entry: BlockPortalEntry): void;
  /**
   * Remove the entry for `id`. Safe (no-op) when absent.
   *
   * Pass the caller's own `hostEl` to make the removal OWNERSHIP-CHECKED: the
   * entry is deleted only when it is still the one that host registered. Core
   * composes a replacement block (which registers under the SAME id) BEFORE it
   * destroys the block it replaces, so a superseded tool's `removed()`/
   * `destroy()` teardown arrives after the live entry is already in place —
   * without the check it deletes that live entry and the holder stays empty.
   */
  unregister(id: string, hostEl?: HTMLElement): void;
  /** Merge `props` into the entry's props (in-place update, no remount). */
  setProps(id: string, props: Record<string, unknown>): void;
  /**
   * Replace the `config` prop of every entry registered under `toolName`, and
   * remember it so entries registered LATER start from this latest config
   * instead of their construction-time snapshot.
   */
  setToolConfig(toolName: string, config: Record<string, unknown>): void;
  /** Subscribe to snapshot changes; returns the unsubscribe function. */
  subscribe(listener: () => void): () => void;
  /** Current immutable snapshot (stable identity until the next mutation). */
  getSnapshot(): ReadonlyMap<string, BlockPortalEntry>;
}

/**
 * Create a fresh portal registry. One per editor instance (associated via the
 * registry map, mirroring the holder WeakMap), so multiple editors on a page
 * never cross-render each other's blocks.
 */
export const createBlockPortalRegistry = (): BlockPortalRegistry => {
  const state = {
    snapshot: new Map<string, BlockPortalEntry>() as ReadonlyMap<string, BlockPortalEntry>,
  };
  const listeners = new Set<() => void>();
  /** Latest per-tool config, applied to mounted entries and future registers. */
  const toolConfigs = new Map<string, Record<string, unknown>>();

  const commit = (next: Map<string, BlockPortalEntry>): void => {
    state.snapshot = next;
    listeners.forEach(listener => listener());
  };

  return {
    register(id: string, entry: BlockPortalEntry): void {
      const next = new Map(state.snapshot);
      const liveConfig = entry.toolName === undefined ? undefined : toolConfigs.get(entry.toolName);

      next.set(
        id,
        liveConfig === undefined ? entry : { ...entry, props: { ...entry.props, config: liveConfig } }
      );
      commit(next);
    },
    unregister(id: string, hostEl?: HTMLElement): void {
      const current = state.snapshot.get(id);

      if (current === undefined) {
        return;
      }

      // A superseded owner may not evict the entry that replaced it.
      if (hostEl !== undefined && current.hostEl !== hostEl) {
        return;
      }

      const next = new Map(state.snapshot);

      next.delete(id);
      commit(next);
    },
    setProps(id: string, props: Record<string, unknown>): void {
      const current = state.snapshot.get(id);

      if (current === undefined) {
        return;
      }

      const next = new Map(state.snapshot);

      next.set(id, { ...current, props: { ...current.props, ...props } });
      commit(next);
    },
    setToolConfig(toolName: string, config: Record<string, unknown>): void {
      toolConfigs.set(toolName, config);

      const matching = [...state.snapshot].filter(([, entry]) => entry.toolName === toolName);

      if (matching.length === 0) {
        return;
      }

      const next = new Map(state.snapshot);

      for (const [id, entry] of matching) {
        next.set(id, { ...entry, props: { ...entry.props, config } });
      }

      commit(next);
    },
    subscribe(listener: () => void): () => void {
      listeners.add(listener);

      return (): void => {
        listeners.delete(listener);
      };
    },
    getSnapshot(): ReadonlyMap<string, BlockPortalEntry> {
      return state.snapshot;
    },
  };
};
